services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  cvision:
    build: ./app
    image: mohamedkhalilzrelly/cvision:latest
    container_name: cvision
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - ./app/.env
    depends_on:
      - mongodb
    volumes:
      - ./app/src:/app/src
      - ./app/src/docs:/app/src/docs
      - ./app/src/data:/app/src/data

volumes:
  mongo_data:
